### ISSUE TITLE
An exception or error caused a run to abort. This may have been caused by a problematic custom reporter.

### ISSUE THREAD

**Issue by Banu27** [maiflai/gradle-scalatest#104]
Full Stacktrace:

An exception or error caused a run to abort. This may have been caused by a problematic custom reporter.
java.lang.RuntimeException: Error creating extended parser class: null
        at org.parboiled.Parboiled.createParser(Parboiled.java:58)
        at org.pegdown.PegDownProcessor.<init>(PegDownProcessor.java:94)
        at org.pegdown.PegDownProcessor.<init>(PegDownProcessor.java:73)
        at org.pegdown.PegDownProcessor.<init>(PegDownProcessor.java:54)
        at org.pegdown.PegDownProcessor.<init>(PegDownProcessor.java:47)
        at org.scalatest.tools.HtmlReporter.<init>(HtmlReporter.scala:117)
        at org.scalatest.tools.ReporterFactory.createHtmlReporter(ReporterFactory.scala:188)
        at org.scalatest.tools.ReporterFactory.getReporterFromConfiguration(ReporterFactory.scala:239)
        at org.scalatest.tools.ReporterFactory$$anonfun$createReportersFromConfigurations$1.apply(ReporterFactory.scala:248)
        at org.scalatest.tools.ReporterFactory$$anonfun$createReportersFromConfigurations$1.apply(ReporterFactory.scala:247)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
        at scala.collection.Iterator$class.foreach(Iterator.scala:743)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1177)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
        at org.scalatest.tools.ReporterConfigurations.foreach(ReporterConfiguration.scala:42)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
        at org.scalatest.tools.ReporterConfigurations.map(ReporterConfiguration.scala:42)
        at org.scalatest.tools.ReporterFactory.createReportersFromConfigurations(ReporterFactory.scala:247)
        at org.scalatest.tools.ReporterFactory.getDispatchReporter(ReporterFactory.scala:251)
        at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1504)
        at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1010)
        at org.scalatest.tools.Runner$.main(Runner.scala:827)
        at org.scalatest.tools.Runner.main(Runner.scala)
Caused by: java.lang.IllegalStateException
        at org.objectweb.asm.tree.analysis.BasicInterpreter.<init>(BasicInterpreter.java:66)
        at org.parboiled.transform.RuleMethodInterpreter.<init>(RuleMethodInterpreter.java:42)
        at org.parboiled.transform.InstructionGraphCreator.process(InstructionGraphCreator.java:41)
        at org.parboiled.transform.ParserTransformer.runMethodTransformers(ParserTransformer.java:62)
        at org.parboiled.transform.ParserTransformer.extendParserClass(ParserTransformer.java:45)
        at org.parboiled.transform.ParserTransformer.transformParser(ParserTransformer.java:38)
        at org.parboiled.Parboiled.createParser(Parboiled.java:54)
        ... 23 more

Version:
Gradle 5.6.4
Scalatest: gradle.plugin.com.github.maiflai:gradle-scalatest:0.25

pegdown version is already pinned at 1.6.0 which seems to be the latest.
Weirdly, I'm not sure what has changed in my build to cause this issue. I have checked asm versions, scalaTest versions and a couple of others and everything seems exactly the same so not sure how to repro.  

Issue seems similar to here: https://github.com/maiflai/gradle-scalatest/issues/54 but the fixes mentioned do not work for me.

**Comment by Banu27** [comment]
Something else I found is that the issue might be due to upgrading version of asm from     "asm": "org.ow2.asm:asm:5.0.3",
to     "asm": "org.ow2.asm:asm:7.2",

**Comment by maiflai** [comment]
That seems reasonable - are you able to pin asm to this version that is compatible with pegdown?

**Comment by maiflai** [comment]
That seems reasonable - are you able to pin asm to this version that is compatible with pegdown?
