### ISSUE TITLE
java.lang.ClassNotFoundException: com.vladsch.flexmark.ast.Node

### ISSUE THREAD

**Issue by igreenfield** [maiflai/gradle-scalatest#111]
When updating com.vladsch.flexmark:flexmark-all to  version 0.62.2 I get this error:
java.lang.NoClassDefFoundError: com/vladsch/flexmark/ast/Node
	at org.scalatest.tools.ReporterFactory.createHtmlReporter(ReporterFactory.scala:194)
	at org.scalatest.tools.ReporterFactory.getReporterFromConfiguration(ReporterFactory.scala:245)
	at org.scalatest.tools.ReporterFactory.$anonfun$createReportersFromConfigurations$1(ReporterFactory.scala:254)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at org.scalatest.tools.ReporterConfigurations.foreach(ReporterConfiguration.scala:42)
	at scala.collection.TraversableLike.map(TraversableLike.scala:286)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
	at org.scalatest.tools.ReporterConfigurations.map(ReporterConfiguration.scala:42)
	at org.scalatest.tools.ReporterFactory.createReportersFromConfigurations(ReporterFactory.scala:253)
	at org.scalatest.tools.ReporterFactory.getDispatchReporter(ReporterFactory.scala:257)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1472)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:971)
	at org.scalatest.tools.Runner$.main(Runner.scala:775)
	at org.scalatest.tools.Runner.main(Runner.scala)
Caused by: java.lang.ClassNotFoundException: com.vladsch.flexmark.ast.Node
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 19 more

we must update to remove the log4j 1 dependency.

**Comment by maiflai** [comment]
sorry, what version of scalatest are you using please?

**Comment by erikvanoosten** [comment]
I am getting error as well with scalatest 3.1.0.

**Comment by erikvanoosten** [comment]
Error is still there with gradle 8.5 and scalatest 3.2.0.

**Comment by erikvanoosten** [comment]
The error is gone with gradle 8.5, scalatest 3.2.19 and dependency `testRuntimeOnly 'com.vladsch.flexmark:flexmark-all:0.62.2'`.

**Comment by jameskyle** [comment]
confirming the issue is not present with the versions above, 3.2.x, 8.5, 0.62.2. 

However, they come back again if you bump gradle up to the current 8.11.1.
