### ISSUE TITLE
java.lang.NoClassDefFoundError: org/gradle/api/reporting/DirectoryReport

### ISSUE THREAD

**Issue by dpapathanasiou** [maiflai/gradle-scalatest#20]
I've setup my gradle build script according to the instructions found here -- https://plugins.gradle.org/plugin/com.github.maiflai.scalatest -- but when I try to get gradle to do anything, I get this stacktrace, below.

I'm using Gradle 1.4 (I cannot upgrade to the latest version, unfortunately), Groovy: 1.8.6, JVM: 1.7.0_65 on Linux 2.6.32-431.40.2.el6.x86_64 amd64.

```
FAILURE: Build failed with an exception.

* Where:
Build file '/home/me/my-project/build.gradle' line: 21

* What went wrong:
A problem occurred evaluating root project 'my-project'.
> org/gradle/api/reporting/DirectoryReport

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.GradleScriptException: A problem occurred evaluating root project 'my-project'.
        at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:54)
[snip]
Caused by: java.lang.NoClassDefFoundError: org/gradle/api/reporting/DirectoryReport
        at com.github.maiflai.ScalaTestPlugin$_apply_closure1.doCall(ScalaTestPlugin.groovy:23)
        at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:58)
        at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:133)
        at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:113)
        at org.gradle.api.internal.AbstractTask.configure(AbstractTask.java:425)
        at org.gradle.api.internal.AbstractTask.configure(AbstractTask.java:58)
        at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:50)
        at org.gradle.api.internal.Actions$FilteredAction.execute(Actions.java:203)
        at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:110)
        at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:115)
        at org.gradle.api.internal.DefaultDomainObjectCollection.withType(DefaultDomainObjectCollection.java:126)
        at org.gradle.api.DomainObjectCollection$withType.call(Unknown Source)
        at com.github.maiflai.ScalaTestPlugin.apply(ScalaTestPlugin.groovy:21)
        at com.github.maiflai.ScalaTestPlugin.apply(ScalaTestPlugin.groovy)
```

**Comment by maiflai** [comment]
Sorry, it looks to me as though Gradle 1.4 was released in January 2013.

Looking back through the commit history, I think that the latest version of this plugin that will work is 0.3.

Please could you try using 0.3 (or perhaps I can help you upgrade to the latest Gradle release).

Thanks,
Stu.

**Comment by dpapathanasiou** [comment]
Thanks for replying.

I have no control over the gradle version (it's a corporate environment, and I must use 1.4), but I will try v.0.3 of your plugin.

I'll update this issue with what I find out.

**Comment by maiflai** [comment]
Please can I close this issue?
