### ISSUE TITLE
java.lang.NoClassDefFoundError: org/gradle/api/logging/configuration/ConsoleOutput

### ISSUE THREAD

**Issue by provegard** [maiflai/gradle-scalatest#39]
I get this when running `gradlew --stacktrace test`:

```
Caused by: java.lang.NoClassDefFoundError: org/gradle/api/logging/configuration/ConsoleOutput
        at com.github.maiflai.ScalaTestAction.color(ScalaTestAction.groovy:102)
        at com.github.maiflai.ScalaTestAction$color$3.callStatic(Unknown Source)
        at com.github.maiflai.ScalaTestAction.reporting(ScalaTestAction.groovy:124)
        at com.github.maiflai.ScalaTestAction$reporting$0.callStatic(Unknown Source)
        at com.github.maiflai.ScalaTestAction.getArgs(ScalaTestAction.groovy:130)
        at com.github.maiflai.ScalaTestAction.makeAction(ScalaTestAction.groovy:71)
        at com.github.maiflai.ScalaTestAction$makeAction.callStatic(Unknown Source)
        at com.github.maiflai.ScalaTestAction.execute(ScalaTestAction.groovy:30)
        at com.github.maiflai.ScalaTestAction.execute(ScalaTestAction.groovy)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 60 more
```

My gradle version is 2.13.

Any workaround? Does the plugin have a dependency on a specific Gradle version, and if so, which one?

**Comment by maiflai** [comment]
Hi,

Yes, the general expectation is that the current version of the plugin works with the current version of Gradle.

What version combination are you trying to use? The release history suggests that 0.13 was released in response to breaking changes in Gradle 2.14.1, and that 0.14 was released in response to breaking changes in Gradle 3.0.

Thanks,
Stu

**Comment by provegard** [comment]
Ok, I tried version 0.12 of the plugin, and it works with Gradle 2.13! Thanks!
