### ISSUE TITLE
Gradle Scalatest with scala version 2.12 throws IncompatibleClassChangeError

### ISSUE THREAD

**Issue by rashid301** [maiflai/gradle-scalatest#51]
I have a gradle project. I am using scala 2.12.2
I have tried adding scalatest library

`dependencies{
        classpath "gradle.plugin.com.github.maiflai:gradle-scalatest:0.14"
}`
`    apply plugin: 'com.github.maiflai.scalatest'`

`dependencies {
      testCompile 'org.scalatest:scalatest_2.12:3.0.1'
      testRuntime 'org.pegdown:pegdown:1.4.2'
}`

Running `gradle test` throws error
`java.lang.IncompatibleClassChangeError: Implementing class
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.parboiled.transform.ParserTransformer.extendParserClass(ParserTransformer.java:43)
        at org.parboiled.transform.ParserTransformer.transformParser(ParserTransformer.java:38)
        at org.parboiled.Parboiled.createParser(Parboiled.java:54)
        at org.pegdown.PegDownProcessor.<init>(PegDownProcessor.java:92)
        at org.pegdown.PegDownProcessor.<init>(PegDownProcessor.java:71)
        at org.pegdown.PegDownProcessor.<init>(PegDownProcessor.java:52)
        at org.pegdown.PegDownProcessor.<init>(PegDownProcessor.java:45)
        at org.scalatest.tools.HtmlReporter.<init>(HtmlReporter.scala:117)
        at org.scalatest.tools.ReporterFactory.createHtmlReporter(ReporterFactory.scala:192)
        at org.scalatest.tools.ReporterFactory.getReporterFromConfiguration(ReporterFactory.scala:239)
        at org.scalatest.tools.ReporterFactory.$anonfun$createReportersFromConfigurations$1(ReporterFactory.scala:248)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
        at scala.collection.Iterator.foreach(Iterator.scala:929)
        at scala.collection.Iterator.foreach$(Iterator.scala:929)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
        at scala.collection.IterableLike.foreach(IterableLike.scala:71)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
        at org.scalatest.tools.ReporterConfigurations.foreach(ReporterConfiguration.scala:42)
        at scala.collection.TraversableLike.map(TraversableLike.scala:234)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
        at org.scalatest.tools.ReporterConfigurations.map(ReporterConfiguration.scala:42)
        at org.scalatest.tools.ReporterFactory.createReportersFromConfigurations(ReporterFactory.scala:247)
        at org.scalatest.tools.ReporterFactory.getDispatchReporter(ReporterFactory.scala:251)
        at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1498)
        at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1010)
        at org.scalatest.tools.Runner$.main(Runner.scala:827)
        at org.scalatest.tools.Runner.main(Runner.scala)
`

I have tried scalatest gradle plugin 1.6
Tried using pegdown version 1.6
And all other combinations I can think of. But I am not able to fix this.

Is there anyone who is using scala 2.12.2 and successfully running scalatest. I want to know what version worked.

**Comment by maiflai** [comment]
Hi,

Perhaps this is a duplicate of https://github.com/maiflai/gradle-scalatest/issues/46#issuecomment-298909708?

It may be that some other dependency in your build has brought in different versions of asm.

Please could you share the full build?

Thanks,
Stu.

**Comment by rashid301** [comment]
@maiflai Your analysis was correct. I had one more dependency in my project which was adding the old asm in the classpath. After I excluded that one, the error went away.
Thank you so much.

**Comment by maiflai** [comment]
Great, thanks.
