### ISSUE TITLE
Running tests with multiple test classes directories fails

### ISSUE THREAD

**Issue by dbrewster** [maiflai/gradle-scalatest#57]
-oDS -PS8 -R /Users/dbrewster/Development/paxata2/paxata/distributions/hadoop-core/build/classes/java/test -R /Users/dbrewster/Development/paxata2/paxata/distributions/hadoop-core/build/classes/scala/test -u /Users/dbrewster/Development/paxata2/paxata/distributions/hadoop-core/build/test-results/test -h /Users/dbrewster/Development/paxata2/paxata/distributions/hadoop-core/build/reports/tests/test
Successfully started process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/bin/java''
Exception in thread "ScalaTest-main" java.lang.IllegalArgumentException: Runpath must be either zero or two args: List(-p, /Users/dbrewster/Development/paxata2/paxata/distributions/hadoop-core/build/classes/java/test, -p, /Users/dbrewster/Development/paxata2/paxata/distributions/hadoop-core/build/classes/scala/test)
        at org.scalatest.tools.Runner$.parseCompoundArgIntoList(Runner.scala:2111)
        at org.scalatest.tools.Runner$.parseRunpathArgIntoList(Runner.scala:2085)
        at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:929)
        at org.scalatest.tools.Runner$.main(Runner.scala:860)
        at org.scalatest.tools.Runner.main(Runner.scala)

The issue is how the plugin is passing the -R options.  You shouldn't be giving multiple -R args but instead on -R arg with each path separated by a ':' (ignoring windows...)

ScalaTestAction:139

**Comment by maiflai** [comment]
Thanks - is that with a particular version of ScalaTest?
