### ISSUE TITLE
Issue with build when upgrading to java 11

### ISSUE THREAD

**Issue by amitgupta1202** [maiflai/gradle-scalatest#72]
gradle version:  5
scala version: 2.12.4
gradle-scalatest version: 0.23
pegdown version: 1.6.0

the build is hanging and keeps printing following stacktrace

```
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.parboiled.transform.AsmUtils (file:/gradle/caches/modules-2/files-2.1/org.parboiled/parboiled-java/1.1.7/2298c64ce8ee8e2fb37e97e16d7be52f0c7cf61f/parboiled-java-1.1.7.jar) to method java.lang.ClassLoader.findLoadedClass(java.lang.String)
WARNING: Please consider reporting this to the maintainers of org.parboiled.transform.AsmUtils
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
An exception or error caused a run to abort. This may have been caused by a problematic custom reporter.
java.lang.RuntimeException: Error creating extended parser class: null
	at org.parboiled.Parboiled.createParser(Parboiled.java:58)
	at org.pegdown.PegDownProcessor.<init>(PegDownProcessor.java:94)
	at org.pegdown.PegDownProcessor.<init>(PegDownProcessor.java:73)
	at org.pegdown.PegDownProcessor.<init>(PegDownProcessor.java:54)
	at org.pegdown.PegDownProcessor.<init>(PegDownProcessor.java:47)
	at org.scalatest.tools.HtmlReporter.<init>(HtmlReporter.scala:117)
	at org.scalatest.tools.ReporterFactory.createHtmlReporter(ReporterFactory.scala:192)
	at org.scalatest.tools.ReporterFactory.getReporterFromConfiguration(ReporterFactory.scala:239)
	at org.scalatest.tools.ReporterFactory.$anonfun$createReportersFromConfigurations$1(ReporterFactory.scala:248)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at org.scalatest.tools.ReporterConfigurations.foreach(ReporterConfiguration.scala:42)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at org.scalatest.tools.ReporterConfigurations.map(ReporterConfiguration.scala:42)
	at org.scalatest.tools.ReporterFactory.createReportersFromConfigurations(ReporterFactory.scala:247)
	at org.scalatest.tools.ReporterFactory.getDispatchReporter(ReporterFactory.scala:251)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1504)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1010)
	at org.scalatest.tools.Runner$.main(Runner.scala:827)
	at org.scalatest.tools.Runner.main(Runner.scala)
Caused by: java.lang.IllegalStateException
	at org.objectweb.asm.tree.analysis.BasicInterpreter.<init>(BasicInterpreter.java:67)
	at org.parboiled.transform.RuleMethodInterpreter.<init>(RuleMethodInterpreter.java:42)
	at org.parboiled.transform.InstructionGraphCreator.process(InstructionGraphCreator.java:41)
	at org.parboiled.transform.ParserTransformer.runMethodTransformers(ParserTransformer.java:62)
	at org.parboiled.transform.ParserTransformer.extendParserClass(ParserTransformer.java:45)
	at org.parboiled.transform.ParserTransformer.transformParser(ParserTransformer.java:38)
	at org.parboiled.Parboiled.createParser(Parboiled.java:54)
	... 24 more
```

**Comment by amitgupta1202** [comment]
wrongly created, culprit was wrong version of asm being picked because of some other module
